-- MySQL Script generated by MySQL Workbench
-- 03/17/17 18:06:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema want
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema want
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `want` DEFAULT CHARACTER SET utf8 ;
USE `want` ;

-- -----------------------------------------------------
-- Table `want`.`contenttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `want`.`contenttype` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `shortName` VARCHAR(16) NOT NULL,
  `description` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `want`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `want`.`user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `credential` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `want`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `want`.`post` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contentType_id` BIGINT(20) UNSIGNED NOT NULL,
  `contentValue` VARCHAR(256) NULL DEFAULT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `dateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `contentType_fk_idx` (`contentType_id` ASC),
  INDEX `user_fk_idx` (`user_id` ASC),
  CONSTRAINT `post_contentType_fk`
    FOREIGN KEY (`contentType_id`)
    REFERENCES `want`.`contenttype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `want`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `want`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `want`.`tag` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tagName` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `want`.`usertagpost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `want`.`usertagpost` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_id` BIGINT(20) UNSIGNED NOT NULL,
  `post_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `dateModified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `tag_fk_idx` (`tag_id` ASC),
  INDEX `user_fk_idx` (`user_id` ASC),
  INDEX `post_fk_idx` (`post_id` ASC),
  CONSTRAINT `utp_post_fk`
    FOREIGN KEY (`post_id`)
    REFERENCES `want`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `utp_tag_fk`
    FOREIGN KEY (`tag_id`)
    REFERENCES `want`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `utp_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `want`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
